### ISSUE TITLE
Downloads Page

### ISSUE THREAD

**Issue by duane909** [kanbanik/kanbanik#22]
Nothing on the downloads page actually links to something. How do I actually download the application and a runtime??

**Comment by jelkosz** [comment]
Which one does not work for you? I have just tried the 1.0.0 (http://sourceforge.net/projects/kanbanik/files/kanbanik-application-1.0.0.zip/download) which points to sourceforge where the download starts in ~5 seconds (or you can use the direct link in the sourceforge page if you prefer). 

Also I have just tried the windows runtime (https://kanbanik.googlecode.com/files/kanbanik-runtime-win-0.2.1.zip)  and it worked for me without the need to wait. 

Any chance there is some proxy in front of you or something which blocks the downloads for you?

**Comment by duane909** [comment]
There are no links on the page, so all of them do not work.
If there is a proxy or something blocking me, then Comcast is up to its illegal tricks again.
Note: I am running Firefox on Xubuntu so please do not tell me to run Chrome or IE.

**Comment by jelkosz** [comment]
I don't think it has anything to do with the browser.
So, if you go to the https://github.com/kanbanik/kanbanik/wiki/Downloads you should see the table containing:
File, Description, Download Link
(maybe you will need to scroll right).

In case not, than I'll paste you direct links here:
kanbanik:
http://sourceforge.net/projects/kanbanik/files/kanbanik-application-1.0.1.zip/download
runtime:
https://kanbanik.googlecode.com/files/kanbanik-runtime-linux-64-bit-0.2.0.zip

If it still does not work, can you please provide a screenshot of what you see?

**Comment by duane909** [comment]
On my laptop at home I do not get a scroll bar at the bottom and comparing that to what I see at work it looks like the second column is getting cut in half. I am downloading here at work and I will take the files home on a thumb drive.

**Comment by jelkosz** [comment]
Based on your feedback I have changed the download page to be more accessible: https://github.com/kanbanik/kanbanik/wiki/Downloads

Could you please check if now you can see the links properly shown now?

**Comment by duane909** [comment]
Yes, that works much better.
Thank you very much !
